---
title: "Interactive"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
runtime: shiny
author: "Blake Roussel"
date: "April 17, 2018"
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(plotly)
library(tidyr)
library(ggmap)
```

```{r}
con <- dplyr::src_mysql(
  host = "ba-isdsclass-programdev.lsu.edu",
  port = 3306,
  user = 'student',
  password = 'student',
  dbname = "isds_3105") 

```

```{r}
commencement <- tbl(con, 'commencement')
alumnus <- tbl(con, 'alumnus')
currentPosition <- tbl(con, 'currentPosition')
location <- tbl(con, 'location')
internship <- tbl(con,'internship')
organization <- tbl(con,'organization')
title <- tbl(con,'title')
college <- tbl(con, 'college')
graduation <- tbl(con, 'graduation')
graduationTitle <- tbl(con, 'graduationTitle')


```

```{r}
major <-  graduation %>% left_join(graduationTitle, by = c('graduationId', 'graduationId')) %>% left_join(title, by = c('idTitle', 'idTitle')) %>% select(graduationId, majorName)

h <- major %>% left_join(currentPosition, by = c('graduationId', 'graduationId')) %>% select(graduationId, majorName, locationId) %>% left_join(location, by =c('locationId', 'locationId')) 

#2,835 have locationId's the rest are null. However, you can make the assumption to the organizationId accordingly. 
```

```{r}
#This drops all elements with NAs as locationId
h1 <- h %>% collect() %>% drop_na(locationId)

```

```{r}
#This joins mapdata with our table so we can make a map. Its has over 1 million element though so im not sure if its 100% correct.

states <- map_data("state")
h2 <- mutate(h1, region = tolower(stateFull)) 
#right_join(h2,states, by = c('region' = 'region')) -> mmap


```

```{r}
statela <- map_data("county") %>% subset(., region %in% c("louisiana"))
```

```{r}
h2 %>% group_by(majorName, region) %>% summarise(total = n()) -> countstate
left_join(countstate,states, by = c('region' = 'region')) -> test1
h2la <- h2 %>% subset(., region %in% c("louisiana"))
h2la %>% group_by(majorName, city) %>% summarise(total = n()) -> lacountstate
h2la %>% group_by(majorName) %>% summarise(total = n()) -> countstatela


```

```{r}
mappingFunc <- function(df, name) {
  if (!( name  %in% unique(df$majorName))) stop('You need to pick a Major within those avaialble in the dataset')
  ggplot(filter( df , majorName == name )) +
    geom_polygon(data = states, aes(x=long, y=lat, group = group), color = "black") +
    coord_fixed(1.3) +
    guides(fill=F)+
    geom_polygon(aes(x = long, y = lat, group = group, fill = total), color = "black") + 
    coord_fixed(1.3) +
    guides(fill=F) +
    ggtitle( name )
}

```

```{r}

mplottingFunc <- function(df, name) {
  if (!( name  %in% unique(df$majorName))) stop('You need to pick a Major within those avaialble in the dataset')
  ggplot(filter( df , majorName == name )) +
    geom_col(aes(city, total))
}
```

 
Inputs {.sidebar}
-------------------------------------

```{r}
MajorNames <- setNames(unique(h2$majorName), unique(h2$majorName)) %>% as.list()
 selectInput("Major", label = h4("Major"), 
    choices = MajorNames, 
    selected = 'Construction Management')


```

Column {data-width=650}
-----------------------------------------------------------------------

```{r}
renderPlot({
 lacountstate %>% 
    arrange(desc(total)) %>%
    slice(1:5) %>% mplottingFunc(., input$Major)
})
```

Column {data-width=650}
-----------------------------------------------------------------------
```{r}
renderPlot({
  mappingFunc(test1, input$Major)
})
```

```{r}
#top 5 highest demand majors in la
countstatela %>% 
    arrange(desc(total)) %>%
    slice(1:5) %>%
ggplot() +
    geom_col(aes(majorName, total))
```


